### ISSUE TITLE
Test Account Request

### ISSUE THREAD

**Issue by zubeyirtaruz** [yoc-media/visx-sdk-android#24]
Hello Dear,

I want to show ads within the app. I have a Huawei ads account and I want to try mediation on YOC. Do you have a test account so I can try this? I also noticed that in your Huawei mediation adapter Huawei Ads SDK version is outdated. I suggest you update it.

**Comment by zinowsky-yoc** [comment]
Hello,

thanks for reaching out to us.

We have removed all Huawei dependencies, such as OAID, and general support within our SDK from version 3.0.0. This will make the Huawei P30 Pro the last device that may be serviced by us, the mediation adapter reflects the age of the device and its dependencies.

There is currently no plans to add support back in short-to-midterm.
